app:
  dashboard_url: "https://pangolin.hippias.fr"

domains:
  domain1:
    base_domain: "pangolin.hippias.fr"
    cert_resolver: "letsencrypt"

server:
  maxmind_asn_path: "/app/config/GeoLite2/GeoLite2-ASN.mmdb"
  maxmind_db_path:  "/app/config/GeoLite2/GeoLite2-Country.mmdb"

gerbil:
  base_endpoint: "pangolin.hippias.fr"

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true

# email:
#   smtp_host: 
#   smtp_port: 
#   smtp_user: 
#   smtp_secure: 
