name: homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.$HOST
    networks:
      - frontend
    volumes:
      - $JOHNCLOUD_ROOT/homepage/config:/app/config # Make sure your local config directory exists
    labels:
      - pangolin.public-resources.homepage.name=homepage
      - pangolin.public-resources.homepage.full-domain=home.$HOST
      - pangolin.public-resources.homepage.protocol=http
      - pangolin.public-resources.homepage.ssl=true
      - pangolin.public-resources.homepage.targets[0].method=http
      - pangolin.public-resources.homepage.targets[0].port=3000

networks:
  frontend:
    external: true
    name: $TRAEFIK_NETWORK
    