http:
  middlewares:
    # Recommended default middleware for most of the services
    default:
      chain:
        middlewares:
          - default-security-headers
          - gzip
          
    # Add automatically some security headers
    default-security-headers:
      headers:
        browserXssFilter: true                            # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow"
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: true                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 63072000                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        customFrameOptionsValue: "sameorigin"

    # Enable GZIP compression
    gzip:
      compress: {}

tls:
  options:
    default:
      sniStrict: true
      
